# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
# //codex (old code snippet) minecraft_version=26.2
minecraft_version=1.21.4
#yarn_mappings=1.21.4+build.8
loader_version=0.19.3
loom_version=1.17

# Mod Properties
mod_version=1.0
maven_group=com.example
archives_base_name=ironmansuit

# Dependencies
# //codex (old code snippet) fabric_version=0.159.0+26.2
fabric_version=0.119.4+1.21.4
# //codex (old code snippet) sodium_version=mc26.2-0.9.1-fabric
sodium_version=mc1.21.4-0.6.13-fabric
